### ISSUE TITLE
Live demo link broken

### ISSUE THREAD

**Issue by lukehefson** [benbalter/comment-card#15]
Hey! I was perusing the README and noticed that the live demo link is broken :cry:.

```
Internal Server Error

No server available
WEBrick/1.3.1 (Ruby/2.1.0/2013-12-25) at comment-card.herokuapp.com:443
```

**Comment by benbalter** [comment]
Sorry about that @lukehefson. Forgot to add Memcache to the instance when I upgraded `problem_child`. Tested and [should be fixed now](https://github.com/benbalter/comment-card/issues/16).

**Comment by lukehefson** [comment]
Lovely stuff. Btw this is brilliant and I don't know how I missed it before.
