### ISSUE TITLE
Would love a similar UI for viewing + responding to issues

### ISSUE THREAD

**Issue by mollieru** [benbalter/comment-card#24]
As government groups, we are often soliciting input from non-technical folks and/or those unfamiliar w Github. The comment card is hugely helpful (thank you!)...but would also be rad to have a similar streamlined interface for reading and responding to Issues which hides the extraneous technical bits (PRs, code, etc.) so that the barrier to entry is lower for everyone's participation.

**Comment by melodykramer** [comment]
This would be super helpful :+1: :100: for the projects we work on, as well. We welcome comments and would like to point people to GitHub to keep everything in one place, but think masking it/providing this UI would lower the barrier for entry for non-technical SMEs and others in the public who might want to contribute.

**Comment by benbalter** [comment]
To understand the ask better, it sounds like, practically, you're essentially looking for a reimplementation of the issue view, but basically without the header, footer, and sidebar, is that roughly correct?

**Comment by mollieru** [comment]
@benbalter I think that might do the trick. The designer in me would love to test this w a lil bit of user research, but instinctively, that sounds about what I was thinking. 

Might also include rewording 'Issues' to 'Comments' (to match 'Comment card').

**Comment by mollieru** [comment]
Ok this is meta, but screenshot of what this might look like w the extra stuff stripped down:

*Issues/Comments list*
![list](https://cloud.githubusercontent.com/assets/3680494/10377532/cdeaa72e-6dd1-11e5-9835-bfdebb8ad115.png)

*Conversation thread*
![thread](https://cloud.githubusercontent.com/assets/3680494/10377533/d069dcd6-6dd1-11e5-8be0-3fd54a09b221.png)

**Comment by benbalter** [comment]
I assume a chrome extension, etc. that injected a custom stylesheet to hide stuff wouldn't help because it'd require the download/install?

**Comment by melodykramer** [comment]
Yeah, we can't assume browser - and it would require us to say "Download this thing" which I'm hesitant to do.

**Comment by mollieru** [comment]
+1 -- ideally, this is an interface that appears automatically when we have a link on a site that say 'tell us what you think'

**Comment by benbalter** [comment]
WIP over in https://github.com/benbalter/comment-card/pull/25. 

Needs polish (I'm definitely not a designer), but the core functionality is there:

![screen shot 2015-10-08 at 4 53 13 pm](https://cloud.githubusercontent.com/assets/282759/10379622/32c071a0-6ddd-11e5-93d1-6735e5dbd4ae.png)

**Comment by mollieru** [comment]
@benbalter you're a speed man. love it!!

**Comment by melodykramer** [comment]
This is great!

**Comment by wslack** [comment]
Thank you Ben! This will be really helpful.

**Comment by benbalter** [comment]
...[and we're live](https://comment-card.herokuapp.com/benbalter/comment-card/issues/240).

For a first pass, it's read only, but subsequent passes can address #26, and #4 can (commenting and browsing issues). If anyone has any design chops and wants to take a class at cleaning things up, it could sure use it.

**Comment by wslack** [comment]
"504 internal server error" on my iPhone fyi

**Comment by benbalter** [comment]
Typo'd the link.

...[and we're live](https://comment-card.herokuapp.com/benbalter/comment-card/issues/24).
